export {default as Checkout} from './checkout/Checkout'
export {default as Confirmation} from './checkout/Confirmation'
export {default as Navbar} from './global/Navbar'
export {default as ItemDetails} from './itemDetails/ItemDetails'
export {default as Home} from './home/Home'